#!/usr/bin/env bash

set -euo pipefail

STATE_FILE="${BIRD_STATE_FILE:-$HOME/.local/share/bird-rust/state/current-install.env}"

if [[ ! -f "$STATE_FILE" ]]; then
  echo "No cutover state file found at $STATE_FILE" >&2
  exit 1
fi

# Generated by cutover-rust-bird.sh and only contains shell-escaped values.
source "$STATE_FILE"

if [[ -z "${link_path:-}" ]]; then
  echo "State file is missing link_path" >&2
  exit 1
fi

if [[ "${previous_kind:-}" == "symlink" && -n "${previous_target:-}" ]]; then
  rm -f "$link_path"
  ln -s "$previous_target" "$link_path"
  echo "Restored symlink: $link_path -> $previous_target"
  exit 0
fi

if [[ "${previous_kind:-}" == "file" && -n "${previous_backup:-}" && -f "${previous_backup:-}" ]]; then
  install -m 755 "$previous_backup" "$link_path"
  echo "Restored file: $link_path"
  exit 0
fi

rm -f "$link_path"
echo "Removed Rust bird link at $link_path; there was no previous install to restore."
